### ISSUE TITLE
Reunião de Alinhamento da Sprint 1

### ISSUE THREAD

**Issue by feeluiz** [ProfKleberSouza/projeto-pratico-brunosamuelfernandogleydiston#13]
- [x] - Definir Estrutura dos "commits"
- [x] - Descutir sobre padrão de gerência de tags, merges, commits e branchs é realizada.
- [x] - Definir qual será o serviço de hospedagem

**Comment by feeluiz** [comment]
**Se tiver mais algum assunto para reunião de quarta, favor listar aqui**

**Comment by bkelsen** [comment]
Por favor deem uma olhada no projeto de interface.
Pode haver algo que eu esteja esquecendo e agora com o protótipo finalizado, 
pode facilitar as e indicar pontos para complementar as outras etapas da Sprint 1.
Amanhã continuo dando sequencia.
