### ISSUE TITLE
Reunião

### ISSUE THREAD

**Issue by ghost** [ProfKleberSouza/projeto-pratico-brunosamuelfernandogleydiston#18]
Definições.

**Comment by bkelsen** [comment]
@feeluiz @gleydiston @LeumasLC 

Segue um tutorial para desenvolvimento em flutter, já comecei aqui uma base e devo subir o código-fonte até sexta-feira 16/04.

http://www.macoratti.net/19/06/flut_intro1.htm

**Comment by bkelsen** [comment]
@feeluiz você pode criar a pasta para o código-fonte para que eu possa colocar commitar nela o develop
